export const overalTypes = {
  LOAD_CURRENCIES: 'LOAD_CURRENCIES',
  LOAD_CURRENCIES_SUCCES: 'LOAD_CURRENCIES_SUCCES',
  LOAD_CURRENCIES_FAILED: 'LOAD_CURRENCIES_FAILED',

  SET_CURRENT_CURRENCY: 'SET_CURRENT_CURRENCY',

  LOAD_CATEGORIES: 'LOAD_CATEGORIES',
  LOAD_CATEGORIES_SUCCESS: 'LOAD_CATEGORIES_SUCCESS',
  LOAD_CATEGORIES_FAILED: 'LOAD_CATEGORIES_FAILED',

  SET_CURRENT_CATEGORY: 'SET_CURRENT_CATEGORY',
}

export const productTypes = {
  LOAD_PRODUCTS_BY_CATEGORY: 'LOAD_PRODUCTS_BY_CATEGORY',
  LOAD_PRODUCTS_BY_CATEGORY_SUCCES: 'LOAD_PRODUCTS_BY_CATEGORY_SUCCES',
  LOAD_PRODUCTS_BY_CATEGORY_FAILED: 'LOAD_PRODUCTS_BY_CATEGORY_FAILED',
}